### ISSUE TITLE
Does not work on Darktable 2.4.0

### ISSUE THREAD

**Issue by MrTango** [theres/dt_timelapse#1]
Hi, i just ried your script on Darktable 2.4.0, but it does not work.

I got the following error:

`LUA ERROR : field "changed_callback" can't be written for type lua_entry`

are the any üplans to contiue this plugin?

**Comment by theres** [comment]
Hi @MrTango 
Right now this plugin require some additional changes in Darktable codebase to work that are not available yet, I need some time to polish code before pull request. I've plans to continue this but in a little less busy time.

However, for timelapse you can use this plugin: https://github.com/darktable-org/lua-scripts/blob/master/contrib/video_mencoder.lua - it base on `mencoder` instead of `ffmpeg`, but essentially it do the job.

**Comment by supertobi** [comment]
Hi,
I wrote the video_mencoder.lua, but mencoder is no longer in the major distributions. It would be nice if you could bring your code up to date an then push it to https://github.com/darktable-org/lua-scripts/ . I would then remove video_mencoder.lua scripts.

**Comment by supertobi** [comment]
Any news here?

**Comment by theres** [comment]
Hi, I've add this to my todo. I hope to have something till end of week.

**Comment by theres** [comment]
It finally get merged to the main lua-scripts repo  (https://github.com/darktable-org/lua-scripts/pull/157)

Closing, this repo gets deprecated now :)
